package app

import (
	"event-service/db"
	"event-service/pb"
	"event-service/server"
	"fmt"
	"github.com/gin-gonic/gin"
	"google.golang.org/grpc"
	"log"
	"net"
)

// refactored to a separate function to switch easily
func setupGinServer() {
	// configure db connection in here
	dbConfig := db.GetPostgresConnection()
	dbInstance, _ := dbConfig.DB()
	defer dbInstance.Close() // graceful connection termination

	// initialize the routers
	r := gin.Default()
	// configure application routes
	r = ConfigureAppRoutes(r, dbConfig)
	// run the servers
	r.Run()
}

// gRPC server setup
func setUpGRPCServer() {
	// configuring the db
	dbConfig := db.GetPostgresConnection()
	dbInstance, _ := dbConfig.DB()
	// defer to shut down gracefully
	defer dbInstance.Close()
	// init grpc server
	grpcServer := grpc.NewServer()
	// custom implementation of EventServer generated by protoc
	eventServer := server.GetNewEventServer(dbConfig)
	// registering event server with grpc server
	pb.RegisterEventServer(grpcServer, eventServer)

	// init tcp service on port 8000
	listener, err := net.Listen("tcp", ":8000")
	if err != nil {
		panic(err.Error())
	}
	log.Println(fmt.Sprintf("Serving at location %v", listener.Addr().String()))
	// serving grpcServer
	grpcServer.Serve(listener)
}

func StartApp() {
	//setupGinServer()
	setUpGRPCServer()
}